# Default values for the prometheus tibber-exporter container
image:
  repository: gunnaringe/tibber-exporter
  pullPolicy: IfNotPresent
  tag: latest

env:
  TZ: UTC
  PUID: "1001"
  PGID: "1001"
  TIBBER_TOKEN: "personal token from tibber"

service:
  main:
    ports:
      http:
        port: "9501"

serviceMonitor:
  labels: {}