apiVersion: v1
name: api-graphql
description: A Helm chart for Kubernetes
type: application
version: 0.6.0
appVersion: master

dependencies:
  - name: common
    version: 2.1.1
    repository: https://k8s-at-home.com/charts/