apiVersion: v1
name: whoami
description: Simple webserver used for diagnostics
type: application
version: 0.8.0
appVersion: latest

dependencies:
  - name: common
    version: 2.2.1
    repository: https://k8s-at-home.com/charts/
