# Defaults values for the prometheus snmp-exporter container
image:
  repository: prom/snmp-exporter
  pullPolicy: IfNotPresent
  tag: v0.20.0


env:
  TZ: UTC
  PUID: "1001"
  PGID: "1001"

service:
  main:
    ports:
      http:
        port: "9116"

serviceMonitor:
  labels:
    release: kube-prometheus-stack
