dependencies:
- name: cheddar
  version: 0.1.0
  repository: https://raw.githubusercontent.com/dniel/Charts/master
  condition: cheddar.enabled, global.cheddar.enabled
  tags:
    - front-end
    - cheddar

- name: stilton
  version: 0.1.0
  repository: https://raw.githubusercontent.com/dniel/Charts/master
  condition: stilton.enabled, global.stilton.enabled
  tags:
    - front-end
    - stilton

- name: wensleydale
  version: 0.1.0
  repository: https://raw.githubusercontent.com/dniel/Charts/master
  condition: wensleydale.enabled, global.wensleydale.enabled
  tags:
    - front-end
    - wensleydale
